# Library

In [1]:
import pandas as pd

# Data

In [2]:
dist_data_properti = pd.read_csv("/mnt/extended-home/ismaprasetiyadi/skripsi/data/data_rumah_dengan_jarak_fasilitas.csv")
dist_data_properti.head(5)

,Harga_Asli,kecamatan,bedroom,bathrooms,jumlah_guest_toilet,list_facilities,list_buildings,lantai,area_digunakan,luas_tanah,...,dist_Universitas,dist_Fasilitas_Kesehatan,dist_Mall,dist_Supermarket,dist_Minimarket,dist_Stasiun,dist_Terminal,dist_Bandara,dist_Halte,dist_Entry_Exit_Tol
0,385000000,Wonoayu,2,1,1,"Internet, Air, Tanpa perabotan, Halaman, Listrik","Keamanan, Taman, Keamanan 24 jam, Area anak-an...",1,34,10,...,10.829117,5.527251,9.865963,8.244602,6.644070,5.362372,6.297998,21.386883,5.362372,29.866557
1,540000000,Sedati,2,1,1,"Garasi, AC, Kabel video, Air, Tanpa perabotan,...","Keamanan, Gym, Taman, Rumah jaga, Keamanan 24 ...",1,32,32,...,2.352266,2.209702,6.722774,5.299212,2.808094,4.825077,2.463128,2.463128,4.825077,8.572197
2,1960000000,Candi,4,3,3,"Garasi, AC, Dapur lengkap, Tangki air, Listrik...","Area anak-anak, Rumah jaga, Taman, Keamanan 24...",3,72,32,...,1.755079,1.545930,3.207815,1.426830,1.484812,1.945620,2.891953,14.379988,2.300403,2.036763
3,950000000,Candi,3,2,2,"Garasi, Halaman, Internet, Tanpa perabotan","Area anak-anak, Taman atap, Taman, Rumah jaga",2,72,32,...,4.077568,2.645925,5.483671,3.289849,0.470766,4.540350,3.610592,15.649330,4.453838,14.222444
4,691000000,Sukodono,2,2,2,"Garasi, Halaman, Tanpa perabotan, Internet, Li...","Keamanan, Rumah jaga, Taman, Keamanan 24 jam",2,72,32,...,6.735769,2.732387,6.101792,2.181219,1.850357,5.118060,6.280646,9.747785,5.118060,20.407812

In [3]:
road_data_properti = pd.read_csv("/mnt/extended-home/ismaprasetiyadi/skripsi/data/data_properti_sidoarjo_with_road_score.csv")
road_data_properti.head(5)

,Harga_Asli,kecamatan,bedroom,bathrooms,jumlah_guest_toilet,list_facilities,list_buildings,lantai,area_digunakan,luas_tanah,latitude,longitude,osm_road_type,road_score
0,385000000,Wonoayu,2,1,1,"Internet, Air, Tanpa perabotan, Halaman, Listrik","Keamanan, Taman, Keamanan 24 jam, Area anak-an...",1,34,10,-7.437160,112.622220,primary,5
1,540000000,Sedati,2,1,1,"Garasi, AC, Kabel video, Air, Tanpa perabotan,...","Keamanan, Gym, Taman, Rumah jaga, Keamanan 24 ...",1,32,32,-7.395451,112.769745,residential,3
2,1960000000,Candi,4,3,3,"Garasi, AC, Dapur lengkap, Tangki air, Listrik...","Area anak-anak, Rumah jaga, Taman, Keamanan 24...",3,72,32,-7.458483,112.700560,tertiary,4
3,950000000,Candi,3,2,2,"Garasi, Halaman, Internet, Tanpa perabotan","Area anak-anak, Taman atap, Taman, Rumah jaga",2,72,32,-7.484486,112.725384,residential,3
4,691000000,Sukodono,2,2,2,"Garasi, Halaman, Tanpa perabotan, Internet, Li...","Keamanan, Rumah jaga, Taman, Keamanan 24 jam",2,72,32,-7.391429,112.698825,residential,3

In [4]:
dist_data_properti["road_score"] = road_data_properti["road_score"]
dist_data_properti.head(3)

,Harga_Asli,kecamatan,bedroom,bathrooms,jumlah_guest_toilet,list_facilities,list_buildings,lantai,area_digunakan,luas_tanah,...,dist_Fasilitas_Kesehatan,dist_Mall,dist_Supermarket,dist_Minimarket,dist_Stasiun,dist_Terminal,dist_Bandara,dist_Halte,dist_Entry_Exit_Tol,road_score
0,385000000,Wonoayu,2,1,1,"Internet, Air, Tanpa perabotan, Halaman, Listrik","Keamanan, Taman, Keamanan 24 jam, Area anak-an...",1,34,10,...,5.527251,9.865963,8.244602,6.644070,5.362372,6.297998,21.386883,5.362372,29.866557,5
1,540000000,Sedati,2,1,1,"Garasi, AC, Kabel video, Air, Tanpa perabotan,...","Keamanan, Gym, Taman, Rumah jaga, Keamanan 24 ...",1,32,32,...,2.209702,6.722774,5.299212,2.808094,4.825077,2.463128,2.463128,4.825077,8.572197,3
2,1960000000,Candi,4,3,3,"Garasi, AC, Dapur lengkap, Tangki air, Listrik...","Area anak-anak, Rumah jaga, Taman, Keamanan 24...",3,72,32,...,1.545930,3.207815,1.426830,1.484812,1.945620,2.891953,14.379988,2.300403,2.036763,4

In [5]:
dist_data_properti.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1241 entries, 0 to 1240
Data columns (total 26 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   Harga_Asli                1241 non-null   int64
 1   kecamatan                 1241 non-null   object
 2   bedroom                   1241 non-null   int64
 3   bathrooms                 1241 non-null   int64
 4   jumlah_guest_toilet       1241 non-null   int64
 5   list_facilities           1241 non-null   object
 6   list_buildings            1241 non-null   object
 7   lantai                    1241 non-null   int64
 8   area_digunakan            1241 non-null   int64
 9   luas_tanah                1241 non-null   int64
 10  latitude                  1241 non-null   float64
 11  longitude                 1241 non-null   float64
 12  dist_SD                   1239 non-null   float64
 13  dist_SMP                  1239 non-null   float64
 14  dist_SMA_SMK              1239 non-null   float64
 15  dist_Universitas          1239 non-null   float64
 16  dist_Fasilitas_Kesehatan  1239 non-null   float64
 17  dist_Mall                 1239 non-null   float64
 18  dist_Supermarket          1240 non-null   float64
 19  dist_Minimarket           1239 non-null   float64
 20  dist_Stasiun              1239 non-null   float64
 21  dist_Terminal             1239 non-null   float64
 22  dist_Bandara              1239 non-null   float64
 23  dist_Halte                1239 non-null   float64
 24  dist_Entry_Exit_Tol       1031 non-null   float64
 25  road_score                1241 non-null   int64
dtypes: float64(15), int64(8), object(3)
memory usage: 252.2+ KB

In [6]:
dist_data_properti["has_exit_tol"] = (~dist_data_properti["dist_Entry_Exit_Tol"].isna()).astype(int)

In [9]:
max_tol = dist_data_properti["dist_Entry_Exit_Tol"].max()
dist_data_properti["dist_Entry_Exit_Tol"] = dist_data_properti["dist_Entry_Exit_Tol"].fillna(max_tol*2)

In [19]:
dist_data_properti.info()
dist_data_properti.tail(3)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1241 entries, 0 to 1240
Data columns (total 27 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   Harga_Asli                1241 non-null   int64
 1   kecamatan                 1241 non-null   object
 2   bedroom                   1241 non-null   int64
 3   bathrooms                 1241 non-null   int64
 4   jumlah_guest_toilet       1241 non-null   int64
 5   list_facilities           1241 non-null   object
 6   list_buildings            1241 non-null   object
 7   lantai                    1241 non-null   int64
 8   area_digunakan            1241 non-null   int64
 9   luas_tanah                1241 non-null   int64
 10  latitude                  1241 non-null   float64
 11  longitude                 1241 non-null   float64
 12  dist_SD                   1239 non-null   float64
 13  dist_SMP                  1239 non-null   float64
 14  dist_SMA_SMK              1239 non-null   float64
 15  dist_Universitas          1239 non-null   float64
 16  dist_Fasilitas_Kesehatan  1239 non-null   float64
 17  dist_Mall                 1239 non-null   float64
 18  dist_Supermarket          1240 non-null   float64
 19  dist_Minimarket           1239 non-null   float64
 20  dist_Stasiun              1239 non-null   float64
 21  dist_Terminal             1239 non-null   float64
 22  dist_Bandara              1239 non-null   float64
 23  dist_Halte                1239 non-null   float64
 24  dist_Entry_Exit_Tol       1241 non-null   float64
 25  road_score                1241 non-null   int64
 26  has_exit_tol              1241 non-null   int64
dtypes: float64(15), int64(9), object(3)
memory usage: 261.9+ KB

,Harga_Asli,kecamatan,bedroom,bathrooms,jumlah_guest_toilet,list_facilities,list_buildings,lantai,area_digunakan,luas_tanah,...,dist_Mall,dist_Supermarket,dist_Minimarket,dist_Stasiun,dist_Terminal,dist_Bandara,dist_Halte,dist_Entry_Exit_Tol,road_score,has_exit_tol
1238,675000000,Krembung,3,2,0,"Garasi, Balkon, Sebagian perabotan, Pendingin ...","Keamanan, Taman",1,765,765,...,13.864110,4.327001,3.249705,5.271919,11.809319,25.558950,5.224404,21.663264,3,1
1239,950000000,Jabon,4,2,0,"Garasi, Tanpa perabotan",Keamanan,1,600,915,...,13.354818,4.852640,4.788847,4.392817,11.481739,23.364833,4.446958,81.195014,2,0
1240,750000000,Krembung,2,1,0,"Garasi, Setengah terpisah, Sebagian perabotan",Taman,1,700,918,...,13.864110,4.327001,3.249705,5.271919,11.809319,25.558950,5.224404,21.663264,3,1

In [20]:
dist_data_properti[dist_data_properti.isna().any(axis=1)]

,Harga_Asli,kecamatan,bedroom,bathrooms,jumlah_guest_toilet,list_facilities,list_buildings,lantai,area_digunakan,luas_tanah,...,dist_Mall,dist_Supermarket,dist_Minimarket,dist_Stasiun,dist_Terminal,dist_Bandara,dist_Halte,dist_Entry_Exit_Tol,road_score,has_exit_tol
14,850000000,Taman,3,2,0,"Garasi, Tangki air, Wifi, AC, Air",Keamanan 24 jam,2,90,36,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,81.195014,5,0
846,2680000000,Waru,4,2,0,"Internet, Tanpa perabotan, Dapur lengkap","Keamanan, Taman",1,90,112,...,NaN,0.0,NaN,NaN,NaN,NaN,NaN,81.195014,2,0

In [21]:
merge_data = dist_data_properti.dropna()
merge_data.info()

<class 'pandas.core.frame.DataFrame'>
Index: 1239 entries, 0 to 1240
Data columns (total 27 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   Harga_Asli                1239 non-null   int64
 1   kecamatan                 1239 non-null   object
 2   bedroom                   1239 non-null   int64
 3   bathrooms                 1239 non-null   int64
 4   jumlah_guest_toilet       1239 non-null   int64
 5   list_facilities           1239 non-null   object
 6   list_buildings            1239 non-null   object
 7   lantai                    1239 non-null   int64
 8   area_digunakan            1239 non-null   int64
 9   luas_tanah                1239 non-null   int64
 10  latitude                  1239 non-null   float64
 11  longitude                 1239 non-null   float64
 12  dist_SD                   1239 non-null   float64
 13  dist_SMP                  1239 non-null   float64
 14  dist_SMA_SMK              1239 non-null   float64
 15  dist_Universitas          1239 non-null   float64
 16  dist_Fasilitas_Kesehatan  1239 non-null   float64
 17  dist_Mall                 1239 non-null   float64
 18  dist_Supermarket          1239 non-null   float64
 19  dist_Minimarket           1239 non-null   float64
 20  dist_Stasiun              1239 non-null   float64
 21  dist_Terminal             1239 non-null   float64
 22  dist_Bandara              1239 non-null   float64
 23  dist_Halte                1239 non-null   float64
 24  dist_Entry_Exit_Tol       1239 non-null   float64
 25  road_score                1239 non-null   int64
 26  has_exit_tol              1239 non-null   int64
dtypes: float64(15), int64(9), object(3)
memory usage: 271.0+ KB

In [22]:
merge_data.to_csv(
    "/mnt/extended-home/ismaprasetiyadi/skripsi/data/final_data.csv",
    index=False
)